### ISSUE TITLE
Getting Started - fix example

### ISSUE THREAD

**Issue by phoe** [zodmaner/trivial-mmap#1]
Just two minor tweaks:

  * The LOOP body can be optimized by using :BELOW, 
  * CHARACTERP does not have any side effects and you are discarding its result value inside DO.

```
CL-USER> (time
           (trivial-mmap:with-mmap-file (ptr size "/home/zodmaner/twitter_rv_15066953.net")
             (loop :for offset :below size :do
               (assert (characterp (trivial-mmap:mmap-read-char ptr offset))))))
```

**Comment by zodmaner** [comment]
Thank you. I have updated the readme with your suggestions.

My loop-fu was weak when I first created this library, so thank you very much for your suggestions, and sorry for the very late reply.
