### ISSUE TITLE
Better to point out: NOT support Windows

### ISSUE THREAD

**Issue by muyinliu** [zodmaner/trivial-mmap#2]
Note: `osicat-posix:mmap` NOT support Windows. There is `CreateFileMapping` on Windows, please check SBCL source code file `src/code/win32.lisp`.

**Comment by zodmaner** [comment]
Thank you for pointing my oversight. I have updated the readme with your suggestion.

Again, thank you for reporting the issue, and sorry for taking so long to reply to you.
